# IMAPX200 Platform Support
snd-soc-imapx200-objs := imapx200-pcm.o
obj-$(CONFIG_SND_IMAPX_SOC) += snd-soc-imapx200.o

snd-soc-imapx200-ac97-objs := imapx200-ac97.o
obj-$(CONFIG_SND_IMAPX200_SOC_AC97) += snd-soc-imapx200-ac97.o

snd-soc-imapx200-i2s-objs := imapx200-i2s.o
obj-$(CONFIG_SND_IMAPX200_SOC_I2S) += snd-soc-imapx200-i2s.o

# ac97 based codec
snd-soc-imapx200-lm4550-objs := imapx200_lm4550.o
obj-$(CONFIG_CODEC_LM4550) += snd-soc-imapx200-lm4550.o

# i2s based codec
snd-soc-imapx200-wm8987-objs := imapx200_wm8987.o
obj-$(CONFIG_CODEC_WM8987) += snd-soc-imapx200-wm8987.o

# i2s based codec
snd-soc-imapx200-es8328-objs := imapx200_es8328.o
obj-$(CONFIG_CODEC_ES8328) += snd-soc-imapx200-es8328.o

# i2s based codec
snd-soc-imapx200-alc5621-objs := imapx200_alc5621.o
obj-$(CONFIG_CODEC_ALC5621) += snd-soc-imapx200-alc5621.o

