#
# Makefile of IMAPX200 bluetooth driver.
#
# Sololz <sololz.luo@gmail.com>.
#

obj-$(CONFIG_IMAPX200_BLUETOOTH_DEVICE_SUPPORT)	+= imapx200_bluetooth.o
obj-$(CONFIG_IMAPX200_BLUETOOTH_DEVICE_RDA5872P) += rda5872p.o
